# Generated by Django 5.0.2 on 2024-02-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_enterproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterproduct',
            name='product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
